# config.yaml

openai:
  api_key_env: "OPENAI_API_KEY"
  model: "gpt-4-0613"
  temperature: 0.85
  max_tokens: 1000
  timeout: 20

run:
  show_output: true
  save_markdown_log: true
  log_folder: "logs"
  max_prompt_length: 1000

principles:
  path: "principles.json"
